### ISSUE TITLE
"Deployment Descriptor" persistence.xml and confusion :)

### ISSUE THREAD

**Issue by schipplock** [agoncal/agoncal-fascicle-jpa#14]
Hi Antonio,
today I bought your fascicle at Amazon and I have to thank you first. I never read a technical book that was so easy to follow. No bloat like "how to install maven" in the middle of the content or "hey, this is how scrum works" :).

However, I have a problem with the chapter "Deployment Descriptor" and the "persistence.xml". You told me to have https://github.com/agoncal/agoncal-fascicle-jpa/blob/master/getting-started/src/main/resources/META-INF/persistence.xml . However, the file references "cdbookstoreCreate.ddl" and "cdbookstoreDrop.ddl".

Where can I find both of these files? And where am I supposed to store them?

**I set up a fresh Ubuntu 18.04 just for this question:**

`apt install maven` (3.6.0)
`apt install openjdk-8-jdk` (javac 1.8.0_212)

I downloaded and started the h2 database (version 1.4.199).

**And then I executed:**

    git clone https://github.com/agoncal/agoncal-fascicle-jpa.git
    cd agoncal-fascicle-jpa
    cd first-step
    mvn test

And it just worked but I don't know why :). I'm an "EE"-noob so be kind to me :).

I'm aware of https://github.com/agoncal/agoncal-fascicle-jpa/blob/master/getting-started/src/main/java/org/agoncal/fascicle/jpa/gettingstarted/artist.ddl and I expected this file to be referenced inside the `persistence.xml`.

Are you willing to clear my confusion? :)

Thanks in advance.

Regards,
Andreas

**Comment by agoncal** [comment]
Hi @schipplock Thanks for your kind words and I'm glad you like my fascicle. To answer your questions. 

```
<property name="javax.persistence.schema-generation.scripts.action" value="drop-and-create"/>
```

This tells the JPA provider (eg. EclipseLink, Hibernate...) that it needs to generate the drop and create scripts. So that means that when you deploy the app, EclipseLink generates the DDL scripts, that's all. The scripts have some default name (I don't know them from the top of my head now, but it's written in the spec).

So the following 2 lines are just telling EclipseLink to give a specific name to those DDL files (`cdbookstoreCreate. ddl` and `cdbookstoreDrop.ddl`). 

```
      <property name="javax.persistence.schema-generation.scripts.create-target" value="cdbookstoreCreate.ddl"/>
      <property name="javax.persistence.schema-generation.scripts.drop-target" value="cdbookstoreDrop.ddl"/>
```

Did I answer your question ?

PS : BTW scrum does not work ;o)

**Comment by schipplock** [comment]
> Did I answer your question ?
yes, thank you :).

> PS : BTW scrum does not work ;o)
hehe! 

Regards,
Andreas
